const books = [
  {
    id: 1,
    title: "O Auto da Compadecida",
    author: "Ariano Suassuna",
    cover: "https://m.media-amazon.com/images/I/81taSo-m23L.jpg",
    category: "Literatura brasileira",
    status: "disponível",
  },
  {
    id: 2,
    title: "Iracema",
    author: "José de Alencar",
    cover:
      "https://www.lpm.com.br/livros/imagens/iracema_9788525421814_9788525406835_hd.jpg",
    category: "Literatura brasileira",
    status: "disponível",
  },
  {
    id: 3,
    title: "Memórias Póstumas de Brás Cubas",
    author: "Machado de Assis",
    cover: "https://m.media-amazon.com/images/I/81Wv6VT-M5S.jpg",
    category: "Literatura brasileira",
    status: "disponível",
  },
  {
    id: 4,
    title: "O Cortiço",
    author: "Aluísio Azevedo",
    cover: "https://m.media-amazon.com/images/I/81m1emiSp-S.jpg",
    category: "Literatura brasileira",
    status: "indisponível",
  },
  {
    id: 5,
    title: "Memórias de um Sargento de Milícias",
    author: "Manuel Antônio de Almeida",
    cover: "https://m.media-amazon.com/images/I/91+Cy1Yj4wL.jpg",
    category: "Literatura brasileira",
    status: "indisponível",
  },
  {
    id: 6,
    title: "O Pequeno Príncipe",
    author: "Antoine de Saint-exupery",
    cover: "https://m.media-amazon.com/images/I/81MscdgdwLL.jpg",
    category: "Infanto-juvenil",
    status: "disponível",
  },
  {
    id: 7,
    title: "Alice no País das Maravilhas",
    author: "Lewis Carroll",
    cover: "https://m.media-amazon.com/images/I/81eAcV387dL.jpg",
    category: "Infanto-juvenil",
    status: "disponível",
  },
  {
    id: 8,
    title: "O Fantasma de Canterville",
    author: "Oscar Wilde",
    cover: "https://m.media-amazon.com/images/I/51Amd6UfYTL.jpg",
    category: "Infanto-juvenil",
    status: "disponível",
  },
  {
    id: 9,
    title: "Robinson Crusoé",
    author: "Daniel Defoe",
    cover: "https://m.media-amazon.com/images/I/91EehIW3CzL.jpg",
    category: "Infanto-juvenil",
    status: "disponível",
  },
  {
    id: 10,
    title: "Mano Descobre a Ecologia",
    author: "Heloisa Prieto / Gilberto Dimenstein",
    cover: "https://m.media-amazon.com/images/I/91wbVj2RZCL.jpg",
    category: "Infanto-juvenil",
    status: "disponível",
  },
  {
    id: 11,
    title: "Viagens de Gulliver",
    author: "Jonathan Swift",
    cover: "https://m.media-amazon.com/images/I/51gT1BfaamL.jpg",
    category: "Infanto-juvenil",
    status: "disponível",
  },
  {
    id: 12,
    title: "Guia Politicamente Incorreto da História do Brasil",
    author: "Leandro Narloch",
    cover:
      "https://m.media-amazon.com/images/I/61S0k9xoSsL._SX342_BO1,204,203,200_.jpg",
    category: "História do Brasil",
    status: "disponível",
  },
  {
    id: 13,
    title: "1968 o Ano Que Não Terminour",
    author: "Zuenir Ventura",
    cover: "https://m.media-amazon.com/images/I/719PJ4MC9BL.jpg",
    category: "História do Brasil",
    status: "disponível",
  },
  {
    id: 14,
    title: "Abolicionismo",
    author: "Joaquim Nabuco",
    cover: "https://m.media-amazon.com/images/I/81ZHk8CjpwL.jpg",
    category: "História do Brasil",
    status: "disponível",
  },
  {
    id: 15,
    title: "Raízes do Brasil",
    author: "Sérgio Buarque de Holanda",
    cover: "https://m.media-amazon.com/images/I/91Tyq-pOAeL.jpg",
    category: "História do Brasil",
    status: "disponível",
  },
  {
    id: 16,
    title: "A Ditadura Escancarada",
    author: "Elio Gaspari",
    cover:
      "https://m.media-amazon.com/images/I/310uirIEBBL._SX346_BO1,204,203,200_.jpg",
    category: "História do Brasil",
    status: "disponível",
  },
  {
    id: 17,
    title: "Rita Lee - uma Autobiografia",
    author: "Rita Lee",
    cover: "https://m.media-amazon.com/images/I/A1KS6wOMXNL.jpg",
    category: "Biografia",
    status: "disponível",
  },
  {
    id: 18,
    title: "Steve Jobs",
    author: "Walter Isaacson",
    cover: "https://m.media-amazon.com/images/I/81wbmWlRNEL.jpg",
    category: "Biografia",
    status: "disponível",
  },
  {
    id: 19,
    title: "O Mago",
    author: "Fernando Morais",
    cover: "https://m.media-amazon.com/images/I/41Zl3iua3cL.jpg",
    category: "Biografia",
    status: "disponível",
  },
  {
    id: 20,
    title: "Gandhi",
    author: "Louis Fischer",
    cover:
      "https://http2.mlstatic.com/D_NQ_NP_681494-MLB50111428542_052022-O.jpg",
    category: "Biografia",
    status: "disponível",
  },
  {
    id: 21,
    title: "Quase Tudo - Memórias",
    author: "Danuza Leão",
    cover: "https://m.media-amazon.com/images/I/71Ja9E3rIxL.jpg",
    category: "Biografia",
    status: "disponível",
  },
  {
    id: 22,
    title: "Chico Buarque",
    author: "Regina Zappa",
    cover: "https://m.media-amazon.com/images/I/515iXV-gUDL.jpg",
    category: "Biografia",
    status: "disponível",
  },
  {
    id: 23,
    title: "Olga",
    author: "Fernando Morais",
    cover: "https://m.media-amazon.com/images/I/816eq6OcZhL.jpg",
    category: "Biografia",
    status: "disponível",
  },
  {
    id: 24,
    title: "Furacão Elis",
    author: "Regina Echeverria",
    cover: "https://m.media-amazon.com/images/I/51ptmPXcgHL.jpg",
    category: "Biografia",
    status: "disponível",
  },
  {
    id: 25,
    title: "O Caçador de Pipas",
    author: "Khaled Hosseini",
    cover: "https://m.media-amazon.com/images/I/81yVzXTgLzL.jpg",
    category: "Literatura Estrangeira",
    status: "disponível",
  },
  {
    id: 26,
    title: "Marley & Eu",
    author: "Grogan, John",
    cover: "https://m.media-amazon.com/images/I/41QIcrrDHvL.jpg",
    category: "Literatura Estrangeira",
    status: "disponível",
  },
  {
    id: 27,
    title: "A Culpa é das Estrelas",
    author: "John Green",
    cover: "https://m.media-amazon.com/images/I/41MRMmeNz0L.jpg",
    category: "Literatura Estrangeira",
    status: "disponível",
  },
  {
    id: 28,
    title: "A Revolução dos Bichos",
    author: "George Orwell",
    cover: "https://m.media-amazon.com/images/I/91BsZhxCRjL.jpg",
    category: "Literatura Estrangeira",
    status: "disponível",
  },
  {
    id: 29,
    title: "Os Três Mosqueteiros",
    author: "Alexandre Dumas",
    cover: "https://m.media-amazon.com/images/I/817bVkQAWhL.jpg",
    category: "Literatura Estrangeira",
    status: "disponível",
  },
  {
    id: 30,
    title: "Orgulho e Preconceito",
    author: "Jane Austen",
    cover: "https://m.media-amazon.com/images/I/61JosO2tkdL.jpg",
    category: "Outros",
    status: "disponível",
  },
];

export default books;
